# BungeeCord configuration
# bungeecord/config.yml

server_connect_timeout: 5000
listeners:
- bind_local_address: true
  force_default_server: false
  forced_hosts:
    creative.aedi.app: creative
    play.aedi.app: creative
    survival.aedi.app: survival
  host: 0.0.0.0:25565
  max_players: 100
  motd: '&7The architecture platform.'
  ping_passthrough: false
  priorities:
  - creative
  - survival
  proxy_protocol: false
  query_enabled: false
  query_port: 25565
  tab_list: GLOBAL_PING
  tab_size: 60
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
log_pings: false
connection_throttle_limit: 3
prevent_proxy_connections: false
timeout: 30000
player_limit: -1
ip_forward: true
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
# edit
stats: statsid
online_mode: true
forge_support: true
disabled_commands:
- viaversion
- viaver
- bungee
- slp
- serverlistplus
- discbot
- geyser
- reconnect
servers:
  creative:
    address: 172.18.0.1:35565
    motd: '&1Just another BungeeCord - Forced Host'
    restricted: false
  survival:
    address: 172.18.0.1:45565
    motd: '&1Just another BungeeCord - Forced Host'
    restricted: false
